quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/topicos1db

#Desabilitar o docker
quarkus.devservices.enabled = false

quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.log.sql = true 
quarkus.hibernate-orm.log.bind-parameters=true
